[from-internal]
exten => _+X.,1,NoOp(Outbound via Plivo (E.164))
 same => n,Set(CALLERID(num)=+912268093829)
 same => n,Set(CALLERID(name)=HotelOpsAI)
 same => n,Dial(PJSIP/${EXTEN}@plivo-trunk,60)
 same => n,Hangup()

exten => _X.,1,NoOp(Outbound via Plivo)
 same => n,Set(CALLERID(num)=+91226809382)
 same => n,Set(CALLERID(name)=HotelOpsAI)
 same => n,Dial(PJSIP/${EXTEN}@plivo-trunk,60)
 same => n,Hangup()


[from-plivo]
exten => s,1,Hangup()
